create table if not exists public.books (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  isbn text not null, title text not null default '', authors text not null default '', publisher text not null default '',
  year text not null default '', cover_url text not null default '', cover_price numeric, condition text not null default 'good',
  notes text not null default '', created_at timestamptz not null default now(), updated_at timestamptz not null default now(),
  unique(user_id,isbn)
);
create table if not exists public.comparables (
  id bigint generated by default as identity primary key,
  book_id bigint not null references public.books(id) on delete cascade,
  platform text not null, url text not null default '', title text not null default '', price numeric not null,
  shipping numeric not null default 0, condition text not null default '', relevance text not null default 'medium',
  evidence_type text not null default 'active', date_label text not null default '', accepted boolean not null default true, observed_at timestamptz not null default now()
);
alter table public.books enable row level security;
alter table public.comparables enable row level security;
create policy "books_owner_all" on public.books for all using (auth.uid()=user_id) with check (auth.uid()=user_id);
create policy "comparables_owner_all" on public.comparables for all
  using (exists(select 1 from public.books where books.id=comparables.book_id and books.user_id=auth.uid()))
  with check (exists(select 1 from public.books where books.id=comparables.book_id and books.user_id=auth.uid()));
