import "jsr:@supabase/functions-js/edge-runtime.d.ts";

const cors = {"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization, x-client-info, apikey, content-type"};
const browserHeaders = {"User-Agent":"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 Chrome/138 Safari/537.36","Accept-Language":"it-IT,it;q=0.9,en;q=0.5","Accept":"text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8"};
type Listing={platform:string;title:string;price:number;shipping:number;currency:"EUR";url:string;relevance:"exact"|"high"|"medium"|"low";condition:string;evidenceType:"active"|"sold"};
const decode=(value="")=>value.replace(/&quot;/g,'"').replace(/&#x27;|&#39;/g,"'").replace(/&amp;/g,"&").replace(/&nbsp;|\u00a0/g," ").replace(/&lt;/g,"<").replace(/&gt;/g,">");
const money=(value="")=>Number(value.replace(/\./g,"").replace(",",".").replace(/[^0-9.]/g,""));
const absolute=(base:string,href:string)=>new URL(decode(href),base).toString();

async function getPage(url:string){const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),18000);try{const response=await fetch(url,{headers:browserHeaders,redirect:"follow",signal:controller.signal});const html=await response.text();return{ok:response.ok,status:response.status,html};}finally{clearTimeout(timer);}}

function parseVinted(html:string):Listing[]{const found:Listing[]=[];for(const block of html.split(/data-testid="grid-item"/i).slice(1)){const href=block.match(/href="(https:\/\/www\.vinted\.it\/items\/[^"]+)"[^>]*data-testid="product-item-id-\d+--overlay-link"/i)?.[1];const title=block.match(/<img[^>]+alt="([^"]+)"[^>]+data-testid="product-item-id-\d+--image--img"/i)?.[1]||block.match(/data-testid="product-item-id-\d+--overlay-link"[^>]+title="([^"]+)"/i)?.[1];const price=block.match(/data-testid="product-item-id-\d+--price-text"[^>]*>([^<]+)/i)?.[1];if(!href||!price||!money(price))continue;found.push({platform:"vinted",title:decode(title||"Annuncio Vinted").replace(/, condizioni:.*$/i,""),price:money(price),shipping:0,currency:"EUR",url:decode(href),relevance:"high",condition:decode(title||"").match(/condizioni:\s*([^,]+)/i)?.[1]||"Usato",evidenceType:"active"});}return found.slice(0,50);}

function parseAbeBooks(html:string):Listing[]{const direct:Listing[]=[];for(const block of html.split(/data-test-id="listing-title-link"/i).slice(1,51)){const href=block.match(/href="([^"]+)"/i)?.[1];const title=block.match(/data-test-id="listing-title"[^>]*>([\s\S]*?)<\/h2>/i)?.[1]?.replace(/<[^>]+>/g,"");const indexedPrice=block.match(/data-test-id="item-price-(\d+)"[\s\S]{0,100}?EUR(?:&nbsp;|\s| )*([0-9.,]+)/i);if(!href||!indexedPrice||!money(indexedPrice[2]))continue;const index=indexedPrice[1];const shipping=block.match(new RegExp(`data-test-id="item-shipping-price-${index}"[\\s\\S]{0,180}?EUR(?:&nbsp;|\\s| )*([0-9.,]+)\\s*spedizione`,"i"))?.[1];const condition=block.match(new RegExp(`data-test-id="listing-book-condition-${index}"[\\s\\S]{0,180}?Condizione:\\s*([^<]+)`,"i"))?.[1]||"Usato";direct.push({platform:"abebooks",title:decode(title||"Offerta AbeBooks"),price:money(indexedPrice[2]),shipping:shipping?money(shipping):0,currency:"EUR",url:absolute("https://www.abebooks.it",href),relevance:"exact",condition:decode(condition),evidenceType:"active"});}if(direct.length)return direct;const books:any[]=[];for(const match of html.matchAll(/<script[^>]+type="application\/ld\+json"[^>]*>([\s\S]*?)<\/script>/gi)){try{const data=JSON.parse(match[1]);for(const element of data.itemListElement||data.mainEntity?.itemListElement||[])if(element?.item?.offers?.price)books.push(element.item);}catch{}}return books.slice(0,50).map(book=>({platform:"abebooks",title:String(book.name||"Offerta AbeBooks"),price:Number(book.offers.price),shipping:0,currency:"EUR",url:String(book.offers.url||book.url),relevance:book.offers.gtin13?"exact":"high",condition:"Usato",evidenceType:"active"}));}

function parseSubito(html:string):Listing[]{const json=html.match(/"items":\{"total":\d+,[\s\S]*?"originalList":(\[[\s\S]*?\]),"galleryList"/)?.[1];if(!json)return[];try{const items=JSON.parse(json);return items.slice(0,50).flatMap((item:any)=>{const price=Number(item.features?.find?.((x:any)=>x.uri==="/price")?.values?.[0]?.value||item.price?.value||item.price||0);const href=item.urls?.default||item.url;if(!price||!href)return[];return[{platform:"subito",title:String(item.subject||item.title||"Annuncio Subito"),price,shipping:0,currency:"EUR" as const,url:absolute("https://www.subito.it",href),relevance:"high" as const,condition:"Usato",evidenceType:"active" as const}];});}catch{return[];}}

function isbn13to10(isbn:string){if(!/^978\d{10}$/.test(isbn))return"";const core=isbn.slice(3,12);let sum=0;for(let i=0;i<9;i++)sum+=Number(core[i])*(10-i);const check=(11-(sum%11))%11;return core+(check===10?"X":check);}
function parseAmazon(html:string,isbn:string):Listing[]{const expected=isbn13to10(isbn),found:Listing[]=[];for(const match of html.matchAll(/<div[^>]+data-asin="([A-Z0-9]{10})"[^>]+data-component-type="s-search-result"[^>]*>([\s\S]*?)(?=<div[^>]+data-asin="[A-Z0-9]{10}"|$)/gi)){const asin=match[1],block=match[2];if(expected&&asin!==expected)continue;const title=block.match(/<h2[^>]+aria-label="([^"]+)"/i)?.[1]||block.match(/<h2[^>]*>[\s\S]*?<span>([^<]+)<\/span>/i)?.[1];const href=block.match(/href="([^"]*\/dp\/[A-Z0-9]{10}[^"]*)"/i)?.[1];const price=block.match(/<span class="a-offscreen">\s*([0-9.,]+)\s*€/i)?.[1];if(!href||!price||!money(price))continue;found.push({platform:"amazon",title:decode(title||"Offerta Amazon"),price:money(price),shipping:0,currency:"EUR",url:absolute("https://www.amazon.it",href),relevance:expected&&asin===expected?"exact":"high",condition:"Nuovo",evidenceType:"active"});}return found.slice(0,10);}
async function amazonUsed(listings:Listing[]){const product=listings[0];if(!product)return[];const page=await getPage(product.url);if(!page.ok)return[];const match=page.html.match(/aria-label="Altri\s+Usato[^"]*?da\s+([0-9.,]+)\s*€/i)||page.html.match(/condition=used_olp[^>]*>[\s\S]{0,180}?a partire da<\/span>\s*([0-9.,]+)\s*€/i);if(!match||!money(match[1]))return[];const asin=product.url.match(/\/dp\/([A-Z0-9]{10})/i)?.[1];return[{...product,title:`${product.title} — offerta usata più economica`,price:money(match[1]),url:`https://www.amazon.it/gp/offer-listing/${asin}?condition=used`,condition:"Usato"}];}
const result=(platform:string,listings:Listing[],note:string,status="not_found")=>({platform,status:listings.length?"found":status,note,listings});

Deno.serve(async req=>{if(req.method==="OPTIONS")return new Response("ok",{headers:cors});try{const{book}=await req.json();if(!book?.isbn)throw new Error("Libro non valido");const isbn=String(book.isbn).replace(/[^0-9X]/gi,"");const urls=[`https://www.vinted.it/catalog?search_text=${encodeURIComponent(isbn)}`,`https://www.ebay.it/sch/i.html?_nkw=${encodeURIComponent(isbn)}`,`https://www.abebooks.it/servlet/SearchResults?isbn=${encodeURIComponent(isbn)}`,`https://www.subito.it/annunci-italia/vendita/libri-riviste/?q=${encodeURIComponent(isbn)}`,`https://www.amazon.it/s?k=${encodeURIComponent(isbn)}`];const[v,e,a,s,z]=await Promise.all(urls.map(getPage));const vl=v.ok?parseVinted(v.html):[],al=a.ok?parseAbeBooks(a.html):[],sl=s.ok?parseSubito(s.html):[],zl=z.ok?parseAmazon(z.html,isbn):[];const used=await amazonUsed(zl);const results=[result("vinted",vl,v.ok?"Ricerca ISBN letta direttamente da Vinted.":`Vinted non accessibile dal server (${v.status}).`,v.ok?"not_found":"blocked"),result("ebay",[],e.ok?"La pagina eBay è accessibile, ma il formato non è ancora leggibile.":`eBay ha bloccato la richiesta automatica (${e.status}).`,"blocked"),result("abebooks",al,a.ok?"Offerte lette direttamente dalla pagina AbeBooks, incluse le spedizioni visibili.":`AbeBooks non accessibile (${a.status}).`,a.ok?"not_found":"blocked"),result("subito",sl,s.ok?"Ricerca ISBN letta direttamente da Subito.":`Subito non accessibile (${s.status}).`,s.ok?"not_found":"blocked"),result("amazon",[...zl,...used],z.ok?"Prezzi letti direttamente da Amazon; l’usato è il minimo indicato nella pagina dell’edizione.":`Amazon non accessibile (${z.status}).`,z.ok?"not_found":"blocked")];return Response.json({results,source:"direct",checkedAt:new Date().toISOString()},{headers:cors});}catch(error){return Response.json({error:error instanceof Error?error.message:"Errore ricerca marketplace"},{status:400,headers:cors});}});
