const wait=ms=>new Promise(resolve=>setTimeout(resolve,ms));
const encode=value=>encodeURIComponent(value);
function isbn13to10(isbn){if(!/^978\d{10}$/.test(isbn))return"";const core=isbn.slice(3,12);let sum=0;for(let i=0;i<9;i++)sum+=Number(core[i])*(10-i);const check=(11-sum%11)%11;return core+(check===10?"X":check);}
function tasks(book){const text=`${book.title} ${book.authors||""}`.trim(),asin=isbn13to10(book.isbn);return[
  {platform:"vinted",url:`https://www.vinted.it/catalog?search_text=${encode(book.isbn)}`},
  {platform:"ebay",url:`https://www.ebay.it/sch/i.html?_nkw=${encode(book.isbn)}`},
  {platform:"ebay",url:`https://www.ebay.it/sch/i.html?_nkw=${encode(text)}&LH_Sold=1&LH_Complete=1`,sold:true},
  {platform:"abebooks",url:`https://www.abebooks.it/servlet/SearchResults?isbn=${encode(book.isbn)}`},
  {platform:"subito",url:`https://www.subito.it/annunci-italia/vendita/libri-riviste/?q=${encode(book.isbn)}`},
  {platform:"amazon",url:`https://www.amazon.it/s?k=${encode(book.isbn)}`,mode:"search"},
  {platform:"amazon",url:`https://www.amazon.it/dp/${asin}`,mode:"offers",active:true}
];}
function loaded(tabId){return new Promise((resolve,reject)=>{const timeout=setTimeout(()=>{chrome.tabs.onUpdated.removeListener(listener);reject(new Error("Tempo scaduto"));},30000);const listener=(id,info)=>{if(id===tabId&&info.status==="complete"){clearTimeout(timeout);chrome.tabs.onUpdated.removeListener(listener);resolve();}};chrome.tabs.onUpdated.addListener(listener);});}
async function scrape(task,book){let tab;try{tab=await chrome.tabs.create({url:task.url,active:Boolean(task.active)});if(tab.status!=="complete")await loaded(tab.id);await wait(task.mode==="offers"?3000:1800);let response;for(let attempt=0;attempt<3;attempt++){try{response=await chrome.tabs.sendMessage(tab.id,{type:"PREZZOLIBRI_SCRAPE",platform:task.platform,mode:task.mode,sold:Boolean(task.sold),isbn:book.isbn,title:book.title,authors:book.authors});break;}catch{await wait(700);}}return{listings:response?.listings||[],diagnostics:response?.diagnostics||null};}catch(error){return{listings:[],diagnostics:{error:error?.message||"Errore scheda"}};}finally{if(tab?.id)await chrome.tabs.remove(tab.id).catch(()=>{});}}
chrome.runtime.onConnect.addListener(port=>{if(port.name!=="prezzolibri-collection")return;port.onMessage.addListener(async message=>{if(message.type!=="START")return;const all=[],diagnostics={},logs=[],work=tasks(message.book);for(let i=0;i<work.length;i++){port.postMessage({type:"PROGRESS",message:`Apro ${work[i].platform}: ricerca ${i+1} di ${work.length}…`});const packet=await scrape(work[i],message.book);all.push(...packet.listings);if(packet.diagnostics){diagnostics[work[i].platform]=packet.diagnostics;logs.push({step:i+1,task:work[i],count:packet.listings.length,...packet.diagnostics});}port.postMessage({type:"PARTIAL",platform:work[i].platform,count:packet.listings.length});}const platforms=["vinted","ebay","abebooks","subito","amazon"];const results=platforms.map(platform=>{const d=diagnostics[platform];const note=d?d.error?`Diagnostica: ${d.error}.`:`Risultati letti dalla tua sessione Chrome (${d.results??0}).`:"Risultati letti dalla tua sessione Chrome.";return{platform,status:all.some(x=>x.platform===platform)?"found":"not_found",note,listings:all.filter(x=>x.platform===platform)}});port.postMessage({type:"COMPLETE",isbn:message.book.isbn,results,logs});});});
