const text=node=>node?.textContent?.replace(/\s+/g," ").trim()||"";
const money=value=>Number(String(value||"").replace(/\./g,"").replace(",",".").replace(/[^0-9.]/g,""));
const absolute=href=>{try{return new URL(href,location.origin).href}catch{return""}};
const listing=(platform,title,price,url,condition="Usato",shipping=0,evidenceType="active",relevance="high")=>({platform,title,price,shipping,url,condition,evidenceType,relevance,currency:"EUR"});
const waitFor=(selector,timeout=8000)=>new Promise(resolve=>{const found=document.querySelector(selector);if(found)return resolve(found);const observer=new MutationObserver(()=>{const node=document.querySelector(selector);if(node){observer.disconnect();clearTimeout(timer);resolve(node);}});observer.observe(document.documentElement,{childList:true,subtree:true});const timer=setTimeout(()=>{observer.disconnect();resolve(null);},timeout);});

function vinted(){return [...document.querySelectorAll('[data-testid$="--overlay-link"]')].flatMap(link=>{const id=link.dataset.testid?.match(/product-item-id-(\d+)/)?.[1];const root=link.closest('[data-testid^="product-item-id-"]')||link.parentElement;const price=money(text(document.querySelector(`[data-testid="product-item-id-${id}--price-text"]`)));const title=link.getAttribute("title")||root?.querySelector("img")?.alt||"Annuncio Vinted";return price?[listing("vinted",title.replace(/, condizioni:.*$/i,""),price,link.href,title.match(/condizioni:\s*([^,]+)/i)?.[1]||"Usato")]:[];});}

function ebay(sold,expectedTitle){const key=String(expectedTitle||"").toLocaleLowerCase("it").match(/[a-zà-ÿ0-9]{5,}/g)?.sort((a,b)=>b.length-a.length)[0]||"";return [...document.querySelectorAll(".s-item, .s-card")].flatMap(root=>{const title=text(root.querySelector(".s-item__title, .s-card__title"));const price=money(text(root.querySelector(".s-item__price, .s-card__price")));const link=root.querySelector("a.s-item__link, a.s-card__link, a[href*='/itm/']")?.href;const rootText=text(root);if(!price||!link||!key||!title.toLocaleLowerCase("it").includes(key)||/Shop on eBay|Esplora eBay/i.test(title)||/REC\.SEED|pg=2334524/i.test(link))return[];if(sold&&!/vendut[oi]\b/i.test(rootText))return[];return[listing("ebay",title,price,link,text(root.querySelector(".SECONDARY_INFO, .s-card__subtitle"))||"Usato",0,sold?"sold":"active","high")];}).slice(0,50);}

async function abebooks(){await waitFor('[data-test-id="listing-title-link"], script[type="application/ld+json"]');const links=[...document.querySelectorAll('[data-test-id="listing-title-link"]')];const direct=links.flatMap((link,index)=>{const priceNode=document.querySelector(`[data-test-id="item-price-${index}"]`)||document.querySelectorAll('[data-test-id^="item-price-"]')[index];const price=money(text(priceNode));const shipping=money(text(document.querySelector(`[data-test-id="item-shipping-price-${index}"]`)));const condition=text(document.querySelector(`[data-test-id="listing-book-condition-${index}"]`)).replace(/^Condizione:\s*/i,"");return price?[listing("abebooks",text(link.querySelector("h2"))||text(link),price,link.href,condition||"Usato",shipping,"active","exact")]:[];}).slice(0,50);if(direct.length)return direct;const fallback=[];for(const script of document.querySelectorAll('script[type="application/ld+json"]')){try{const data=JSON.parse(script.textContent);for(const entry of data.itemListElement||data.mainEntity?.itemListElement||[]){const book=entry.item,offer=book?.offers;if(offer?.price&&offer?.url)fallback.push(listing("abebooks",book.name||"Offerta AbeBooks",Number(offer.price),offer.url,"Usato",0,"active",offer.gtin13?"exact":"high"));}}catch{}}return fallback.slice(0,50);}

function subito(){const seen=new Set();return [...document.querySelectorAll('a[href*=".htm"]')].flatMap(link=>{const root=link.closest("article")||link.parentElement?.parentElement;const match=text(root).match(/(?:€\s*)?(\d+(?:[.,]\d{2})?)\s*€/);const price=money(match?.[1]),url=absolute(link.href);if(!price||!url||seen.has(url))return[];seen.add(url);return[listing("subito",text(root?.querySelector("h2,h3"))||link.getAttribute("title")||"Annuncio Subito",price,url)];}).slice(0,50);}

function isbn13to10(isbn){if(!/^978\d{10}$/.test(isbn))return"";const core=isbn.slice(3,12);let sum=0;for(let i=0;i<9;i++)sum+=Number(core[i])*(10-i);const check=(11-sum%11)%11;return core+(check===10?"X":check);}
async function amazon(isbn){const asin=isbn13to10(isbn);const expected=document.querySelector(`[data-component-type="s-search-result"][data-asin="${asin}"]`)||document.querySelector('[data-component-type="s-search-result"][data-asin]');if(!expected)return[];const title=text(expected.querySelector("h2")),price=money(text(expected.querySelector(".a-price .a-offscreen"))),link=expected.querySelector('a[href*="/dp/"]')?.href;if(!price||!link)return[];const found=[listing("amazon",title,price,link,"Nuovo",0,"active",asin&&expected.dataset.asin===asin?"exact":"high")];try{const html=await fetch(link,{credentials:"include"}).then(r=>r.text());const used=html.match(/aria-label="Altri\s+Usato[^"]*?da\s+([0-9.,]+)\s*€/i),productAsin=link.match(/\/dp\/([A-Z0-9]{10})/i)?.[1];if(used&&productAsin)found.push(listing("amazon",`${title} — offerta usata più economica`,money(used[1]),`https://www.amazon.it/gp/offer-listing/${productAsin}?condition=used`,"Usato",0,"active",productAsin===asin?"exact":"high"));}catch{}return found;}

chrome.runtime.onMessage.addListener((message,_sender,sendResponse)=>{if(message.type!=="PREZZOLIBRI_SCRAPE")return;Promise.resolve(message.platform==="vinted"?vinted():message.platform==="ebay"?ebay(message.sold,message.title):message.platform==="abebooks"?abebooks():message.platform==="subito"?subito():amazon(message.isbn)).then(listings=>sendResponse({listings}));return true;});
