const text=node=>node?.textContent?.replace(/\s+/g," ").trim()||"";
const money=value=>Number(String(value||"").replace(/\./g,"").replace(",",".").replace(/[^0-9.]/g,""));
const absolute=href=>{try{return new URL(href,location.origin).href}catch{return""}};
const listing=(platform,title,price,url,condition="Usato",shipping=0,evidenceType="active",relevance="high")=>({platform,title,price,shipping,url,condition,evidenceType,relevance,currency:"EUR"});
const waitFor=(selector,timeout=8000)=>new Promise(resolve=>{const found=document.querySelector(selector);if(found)return resolve(found);const observer=new MutationObserver(()=>{const node=document.querySelector(selector);if(node){observer.disconnect();clearTimeout(timer);resolve(node);}});observer.observe(document.documentElement,{childList:true,subtree:true});const timer=setTimeout(()=>{observer.disconnect();resolve(null);},timeout);});

function vinted(){return [...document.querySelectorAll('[data-testid$="--overlay-link"]')].flatMap(link=>{const id=link.dataset.testid?.match(/product-item-id-(\d+)/)?.[1];const root=link.closest('[data-testid^="product-item-id-"]')||link.parentElement;const price=money(text(document.querySelector(`[data-testid="product-item-id-${id}--price-text"]`)));const title=link.getAttribute("title")||root?.querySelector("img")?.alt||"Annuncio Vinted";return price?[listing("vinted",title.replace(/, condizioni:.*$/i,""),price,link.href,title.match(/condizioni:\s*([^,]+)/i)?.[1]||"Usato")]:[];});}

function ebay(sold,expectedTitle){const key=String(expectedTitle||"").toLocaleLowerCase("it").match(/[a-zà-ÿ0-9]{5,}/g)?.sort((a,b)=>b.length-a.length)[0]||"";return [...document.querySelectorAll(".s-item, .s-card")].flatMap(root=>{const title=text(root.querySelector(".s-item__title, .s-card__title"));const price=money(text(root.querySelector(".s-item__price, .s-card__price")));const rawLink=root.querySelector("a.s-item__link, a.s-card__link, a[href*='/itm/']")?.href;const rootText=text(root),itemId=rawLink?.match(/\/itm\/(?:[^/?]+\/)?(\d{9,15})/i)?.[1];if(!price||!rawLink||!itemId||!key||!title.toLocaleLowerCase("it").includes(key)||/Shop on eBay|Esplora eBay/i.test(title)||/REC\.SEED|pg=2334524/i.test(rawLink))return[];if(sold&&!/vendut[oi]\b/i.test(rootText))return[];return[listing("ebay",title,price,`https://www.ebay.it/itm/${itemId}`,text(root.querySelector(".SECONDARY_INFO, .s-card__subtitle"))||"Usato",0,sold?"sold":"active","high")];}).slice(0,50);}

async function abebooks(){await waitFor('a[href*="/bd"], [data-test-id="listing-title-link"], script[type="application/ld+json"]');const links=[...document.querySelectorAll('[data-test-id="listing-title-link"]')];const direct=links.flatMap((link,index)=>{const priceNode=document.querySelector(`[data-test-id="item-price-${index}"]`)||document.querySelectorAll('[data-test-id^="item-price-"]')[index];const price=money(text(priceNode));const shipping=money(text(document.querySelector(`[data-test-id="item-shipping-price-${index}"]`)));const condition=text(document.querySelector(`[data-test-id="listing-book-condition-${index}"]`)).replace(/^Condizione:\s*/i,"");return price?[listing("abebooks",text(link.querySelector("h2"))||text(link),price,link.href,condition||"Usato",shipping,"active","exact")]:[];}).slice(0,50);if(direct.length)return direct;const generic=[],seen=new Set();for(const link of document.querySelectorAll('a[href*="/bd"]')){const url=absolute(link.href);if(!/\/\d+\/bd(?:[?#]|$)/i.test(url)||seen.has(url))continue;let card=link;for(let level=0;level<10&&card?.parentElement;level++){card=card.parentElement;const cardText=text(card);if(/EUR\s*[0-9]+[,.][0-9]{2}/i.test(cardText)&&cardText.length<6000)break;}const cardText=text(card),priceMatch=cardText.match(/EUR\s*([0-9]+[,.][0-9]{2})/i);if(!priceMatch)continue;const shippingMatch=cardText.match(/(?:Spedizione\s*)?EUR\s*([0-9]+[,.][0-9]{2})\s*spedizione/i)||cardText.match(/Spedizione\s*EUR\s*([0-9]+[,.][0-9]{2})/i);const condition=cardText.match(/Condizione:\s*([^|\n]+?)(?=\s+(?:EUR|Spedizione|Da:|Quantità)|$)/i)?.[1]||"Usato";seen.add(url);generic.push(listing("abebooks",text(link.querySelector("h2"))||text(link)||"Offerta AbeBooks",money(priceMatch[1]),url,condition,shippingMatch?money(shippingMatch[1]):0,"active","exact"));}if(generic.length)return generic.slice(0,50);const fallback=[];for(const script of document.querySelectorAll('script[type="application/ld+json"]')){try{const data=JSON.parse(script.textContent);for(const entry of data.itemListElement||data.mainEntity?.itemListElement||[]){const book=entry.item,offer=book?.offers;if(offer?.price&&offer?.url)fallback.push(listing("abebooks",book.name||"Offerta AbeBooks",Number(offer.price),offer.url,"Usato",0,"active",offer.gtin13?"exact":"high"));}}catch{}}return fallback.slice(0,50);}

function subito(){const seen=new Set();return [...document.querySelectorAll('a[href*=".htm"]')].flatMap(link=>{const root=link.closest("article")||link.parentElement?.parentElement;const match=text(root).match(/(?:€\s*)?(\d+(?:[.,]\d{2})?)\s*€/);const price=money(match?.[1]),url=absolute(link.href);if(!price||!url||seen.has(url))return[];seen.add(url);return[listing("subito",text(root?.querySelector("h2,h3"))||link.getAttribute("title")||"Annuncio Subito",price,url)];}).slice(0,50);}

function isbn13to10(isbn){if(!/^978\d{10}$/.test(isbn))return"";const core=isbn.slice(3,12);let sum=0;for(let i=0;i<9;i++)sum+=Number(core[i])*(10-i);const check=(11-sum%11)%11;return core+(check===10?"X":check);}
async function amazonSearch(isbn){const asin=isbn13to10(isbn);const expected=document.querySelector(`[data-component-type="s-search-result"][data-asin="${asin}"]`)||document.querySelector('[data-component-type="s-search-result"][data-asin]');if(!expected)return[];const title=text(expected.querySelector("h2")),price=money(text(expected.querySelector(".a-price .a-offscreen"))),link=expected.querySelector('a[href*="/dp/"]')?.href;if(!price||!link)return[];return[listing("amazon",title,price,link,"Nuovo",0,"active",asin&&expected.dataset.asin===asin?"exact":"high")];}
async function amazonOffers(isbn){const asin=isbn13to10(isbn);let rows=[...document.querySelectorAll("#aod-offer")];if(!rows.length){document.querySelector('[data-action="show-all-offers-display"], .aod-popover-caret-link')?.click();await waitFor("#aod-offer, #aod-offer-list",10000);rows=[...document.querySelectorAll("#aod-offer")];}const title=text(document.querySelector("#productTitle"))||"Offerta Amazon usata";const offers=rows.flatMap((row,index)=>{const price=money(text(row.querySelector(".a-price .a-offscreen, .aod-offer-price .a-offscreen")));if(!price)return[];const condition=text(row.querySelector("#aod-offer-heading, .aod-information-block"))||text(row).match(/Usato\s*-\s*[^€]+/)?.[0]||"Usato";const seller=text(row.querySelector("#aod-offer-soldBy a, #aod-offer-soldBy .a-color-base"));return[listing("amazon",`${title}${seller?` — ${seller}`:""}`,price,`https://www.amazon.it/gp/offer-listing/${asin}?condition=used#offer-${index+1}`,condition,0,"active","exact")];});if(offers.length)return offers;const pageText=document.body.innerText||"",generic=[],seen=new Set();for(const match of pageText.matchAll(/(Usato\s*-\s*[^\r\n]+)[\s\r\n]*([0-9]+(?:[,.][0-9]{2}))\s*€/gi)){const condition=match[1].trim(),price=money(match[2]),key=`${condition}|${price}`;if(!price||seen.has(key))continue;seen.add(key);generic.push(listing("amazon",title,price,`https://www.amazon.it/gp/offer-listing/${asin}?condition=used#offer-${generic.length+1}`,condition,0,"active","exact"));}if(generic.length)return generic;const minimum=pageText.match(/Altri\s+Usato[^\n]*?da\s+([0-9.,]+)\s*€/i);return minimum?[listing("amazon",`${title} — offerta usata più economica`,money(minimum[1]),`https://www.amazon.it/gp/offer-listing/${asin}?condition=used`,"Usato",0,"active","exact")]:[];}

chrome.runtime.onMessage.addListener((message,_sender,sendResponse)=>{if(message.type!=="PREZZOLIBRI_SCRAPE")return;Promise.resolve(message.platform==="vinted"?vinted():message.platform==="ebay"?ebay(message.sold,message.title):message.platform==="abebooks"?abebooks():message.platform==="subito"?subito():message.mode==="offers"?amazonOffers(message.isbn):amazonSearch(message.isbn)).then(listings=>sendResponse({listings,diagnostics:message.platform==="abebooks"?{url:location.href,title:document.title,ready:document.readyState,links:document.querySelectorAll('[data-test-id="listing-title-link"]').length,bookLinks:[...document.querySelectorAll('a[href*="/bd"]')].filter(link=>/\/\d+\/bd(?:[?#]|$)/i.test(link.href)).length,prices:document.querySelectorAll('[data-test-id^="item-price-"]').length,jsonLd:document.querySelectorAll('script[type="application/ld+json"]').length,body:document.body?.innerText?.length||0,challenge:/captcha|robot|access denied|non sei un robot/i.test(document.body?.innerText||"")}:null}));return true;});
