const text=(node)=>node?.textContent?.replace(/\s+/g," ").trim()||"";
const money=value=>Number(String(value||"").replace(/\./g,"").replace(",",".").replace(/[^0-9.]/g,""));
const absolute=href=>{try{return new URL(href,location.origin).href}catch{return""}};
const listing=(platform,title,price,url,condition="Usato",shipping=0,evidenceType="active",relevance="high")=>({platform,title,price,shipping,url,condition,evidenceType,relevance,currency:"EUR"});
function ancestorWith(node,selector){for(let parent=node;parent&&parent!==document.body;parent=parent.parentElement)if(parent.querySelector(selector))return parent;return null;}
function vinted(){return [...document.querySelectorAll('[data-testid$="--overlay-link"]')].flatMap(link=>{const id=link.dataset.testid?.match(/product-item-id-(\d+)/)?.[1];const root=link.closest('[data-testid^="product-item-id-"]')||link.parentElement;const price=money(text(document.querySelector(`[data-testid="product-item-id-${id}--price-text"]`)));const title=link.getAttribute("title")||root?.querySelector("img")?.alt||"Annuncio Vinted";return price?[listing("vinted",title.replace(/, condizioni:.*$/i,""),price,link.href,title.match(/condizioni:\s*([^,]+)/i)?.[1]||"Usato")]:[];});}
function ebay(sold){return [...document.querySelectorAll(".s-item")].flatMap(root=>{const title=text(root.querySelector(".s-item__title"));const price=money(text(root.querySelector(".s-item__price")));const link=root.querySelector("a.s-item__link")?.href;if(!price||!link||/Shop on eBay|Esplora eBay/i.test(title))return[];return[listing("ebay",title,price,link,text(root.querySelector(".SECONDARY_INFO"))||"Usato",0,sold?"sold":"active",sold?"medium":"high")];}).slice(0,50);}
function abebooks(){return [...document.querySelectorAll('[data-test-id="listing-title-link"]')].flatMap(link=>{const root=ancestorWith(link,'[data-test-id^="item-price-"]');const priceNode=root?.querySelector('[data-test-id^="item-price-"]');const index=priceNode?.dataset.testId?.match(/(\d+)$/)?.[1]||priceNode?.getAttribute("data-test-id")?.match(/(\d+)$/)?.[1];const price=money(text(priceNode));const shipping=money(text(root?.querySelector(`[data-test-id="item-shipping-price-${index}"]`)));const condition=text(root?.querySelector(`[data-test-id="listing-book-condition-${index}"]`)).replace(/^Condizione:\s*/i,"");return price?[listing("abebooks",text(link.querySelector("h2"))||text(link),price,link.href,condition||"Usato",shipping,"active","exact")]:[];}).slice(0,50);}
function subito(){const seen=new Set();return [...document.querySelectorAll('a[href*=".htm"]')].flatMap(link=>{const root=link.closest("article")||link.parentElement?.parentElement;const blob=text(root);const match=blob.match(/(?:€\s*)?(\d+(?:[.,]\d{2})?)\s*€/);const price=money(match?.[1]);const url=absolute(link.href);if(!price||!url||seen.has(url))return[];seen.add(url);return[listing("subito",text(root?.querySelector("h2,h3"))||link.getAttribute("title")||"Annuncio Subito",price,url)];}).slice(0,50);}
function isbn13to10(isbn){if(!/^978\d{10}$/.test(isbn))return"";const core=isbn.slice(3,12);let sum=0;for(let i=0;i<9;i++)sum+=Number(core[i])*(10-i);const check=(11-sum%11)%11;return core+(check===10?"X":check);}
async function amazon(isbn){const asin=isbn13to10(isbn);const expected=document.querySelector(`[data-component-type="s-search-result"][data-asin="${asin}"]`)||document.querySelector('[data-component-type="s-search-result"][data-asin]');if(!expected)return[];const title=text(expected.querySelector("h2"));const price=money(text(expected.querySelector(".a-price .a-offscreen")));const link=expected.querySelector('a[href*="/dp/"]')?.href;if(!price||!link)return[];const found=[listing("amazon",title,price,link,"Nuovo",0,"active",asin&&expected.dataset.asin===asin?"exact":"high")];try{const html=await fetch(link,{credentials:"include"}).then(r=>r.text());const used=html.match(/aria-label="Altri\s+Usato[^"]*?da\s+([0-9.,]+)\s*€/i);const productAsin=link.match(/\/dp\/([A-Z0-9]{10})/i)?.[1];if(used&&productAsin)found.push(listing("amazon",`${title} — offerta usata più economica`,money(used[1]),`https://www.amazon.it/gp/offer-listing/${productAsin}?condition=used`,"Usato",0,"active",productAsin===asin?"exact":"high"));}catch{}return found;}
chrome.runtime.onMessage.addListener((message,_sender,sendResponse)=>{if(message.type!=="PREZZOLIBRI_SCRAPE")return;Promise.resolve(message.platform==="vinted"?vinted():message.platform==="ebay"?ebay(message.sold):message.platform==="abebooks"?abebooks():message.platform==="subito"?subito():amazon(message.isbn)).then(listings=>sendResponse({listings}));return true;});
